version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "aioresponses"
          - "freezegun"
          - "prek"
          - "pytest-asyncio"
          - "pytest-cov"
          - "pytest-error-for-skips"
          - "pytest-homeassistant-custom-component"
          - "pytest-timeout"
          - "pytest"
          - "ruff"
          - "syrupy"
          - "ty"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
